version: '3.7'
services:
  # file-storage
  file-storage:
    image: golang:1.19
    expose:
      - "8080:8080" # gRPC
      - "8081:8081" # HTTP
    tty: true
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      APP_ENV: dev
      SERVER_PORT: 8080
      MINIO_HOST: minio:9000
      MINIO_ACCESS_KEY_ID: minioadmin
      MINIO_SECRET_ACCESS_KEY: minioadmin
      OTEL_AGENT: http://jaeger:14268/api/traces
    volumes:
      - ..:/app
    working_dir: /app
    command: |
      go run ./cmd/main.go
    depends_on:
      - minio
      - jaeger
    networks:
      - fullstack
  # minio
  minio:
    image: minio/minio:RELEASE.2023-02-22T18-23-45Z
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web user interface
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ADDRESS: ":9000"
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data
    networks:
      - fullstack
  # createbuckets
  createbuckets:
    image: minio/mc:RELEASE.2023-02-16T19-20-11Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/default;
      /usr/bin/mc mb myminio/default;
      /usr/bin/mc policy download myminio/default;
      exit 0;
      "
    networks:
      - fullstack
  # jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    ports:
      - "14268:14268"   # jaeger-collector HTTP server (tracer provider)
      - "16686:16686"   # HTTP server (browser UI)
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge
